# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    node_encrypt:
      repo: 'https://github.com/binford2k/binford2k-node_encrypt.git'
      ref: '868021745829a204c5c2028bdec972a2f4dc926a'
    ssh:
      repo: "https://github.com/ploperations/ploperations-ssh"
      tag: "0.9.0"
    zsh:
      repo: "https://github.com/ploperations/ploperations-zsh"
      ref: "78e1e1b866dd8082768ce5cef60b0e3680a79137"
  forge_modules:
    # Most of these are dependencies of puppetlabs/ssh.
    acl: "puppetlabs/acl"
    bash: "ploperations/bash"
    chocolatey: "puppetlabs/chocolatey"
    classification: "ploperations/classification"
    concat: "puppetlabs/concat"
    cygwin: "mdelaney/cygwin"
    # node_encrypt: "binford2k/node_encrypt" need 0.4.1 or later
    registry: "puppetlabs/registry"
    windows_env: "puppet/windows_env"
    sshkeys_core: "puppetlabs/sshkeys_core"
    stdlib: "puppetlabs/stdlib"
    # zsh: "ploperations/zsh"
